[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 20

# [[main]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 30

# [[main]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 40

[[main]]
  identifier = "rss"
  name = "RSS"
  weight = 70
  url = "/index.xml"
  [main.params]
    icon = "rss"
    showName = false
    target = "_blank"

[[main]]
  identifier = "appearance"
  weight = 80
  [main.params]
    action = "appearance"

[[main]]
  identifier = "search"
  weight = 90
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
