---
name: Build and Push Container

on:
  push:
    branches:
      - main

jobs:
  container-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Container Image Tag
        id: image_tag
        run: |
          ref=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          timestamp=$(date +%s)
          echo "::set-output name=image_tag::${ref}-${sha}-${timestamp}"  

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Container
        uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: true
          tags: |
            ghcr.io/sudomateo/website:latest
            ghcr.io/sudomateo/website:${{ github.sha }}
            ghcr.io/sudomateo/website:${{ steps.image_tag.outputs.image_tag }}
          platforms: |
            linux/amd64
            linux/arm64
